name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to docker hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Build docker image
        run: docker build -t imrohit68/youtube-upload .
      - name: Publish image to docker hub
        run: docker push imrohit68/youtube-upload:latest

  deploy:
    needs: build
    runs-on: [ubuntu-latest]
    steps:
      - name: Key Gen
        run: echo "${{ secrets.SSH_KEY}}" >> jenkins.pem
      - name: Give permissions
        run: chmod 600 jenkins.pem
      - name: Execute Commands on Remote Server
        run:  ssh -o StrictHostKeyChecking=no -i jenkins.pem ubuntu@ec2-3-82-251-117.compute-1.amazonaws.com "sudo docker pull imrohit68/youtube-upload:latest && sudo docker run -d -p 8080:8080 --name print-app-container imrohit68/youtube-upload "
