name: CICD

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build Project
        run: mvn clean install -DskipTests
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t imrohit68/youtube-upload:latest .
      - name: Publish Image to Docker Hub
        run: docker push imrohit68/youtube-upload:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    env:
      EC2_SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}
    steps:
      - name: Setup SSH for EC2
        uses: omarhosny206/setup-ssh-for-ec2@v1.0.0
        with:
          EC2_SSH_PRIVATE_KEY: ${{ env.EC2_SSH_PRIVATE_KEY }}
          EC2_URL: ${{ env.EC2_URL }}
      - name: Clean Up Old Docker Resources
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USERNAME }}@${{ env.EC2_URL }} "sudo docker image prune -a -f"
      - name: Pull Latest Docker Image
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USERNAME }}@${{ env.EC2_URL }} "sudo docker pull imrohit68/youtube-upload:latest"
      - name: Stop and Remove Old Container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USERNAME }}@${{ env.EC2_URL }} "sudo docker rm -f youtube-upload-container"
      - name: Run New Container
        run: |
          ssh -o StrictHostKeyChecking=no ${{ env.EC2_USERNAME }}@${{ env.EC2_URL }} "sudo docker run -d -p 8090:8080 --name youtube-upload-container \
          -e spring.datasource.password='${{ secrets.DATABASE_PASSWORD }}' \
          -e google.client.id='${{ secrets.CLIENT_ID }}' \
          -e google.client.secret='${{ secrets.CLIENT_SECRET }}' \
          -e google.redirect.uri='${{ secrets.REDIRECT_URI }}' \
          -e algorithm.secret='${{ secrets.ALGO_SECRET }}' \
          -e encryption.key='${{ secrets.ENCRYPTION_KEY }}' \
          -e spring_profiles_active=prod imrohit68/youtube-upload:latest"
